### ISSUE TITLE
exercise book: pg ii (pdf pg 5) mentions "Calculus 4" and Math 317

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#32]
> Types of Questions
> 
> Q[1]( ̊): In addition to original problems, this book contains problems pulled from
> quizzes and exams given at UBC for Math 317 (Calculus 4).  These problems
> are marked with a star.

I think that should be something like "at UBC for Math 200 and Math 253 and other Calculus 3-level courses".

**Comment by arechnitzer** [comment]
Is this in the stand-alone problem book or in the combined text?
(and thanks for reporting this and other issues)

**Comment by cbm755** [comment]
It was the stand-alone problem book, Aug 28th print date.

**Comment by arechnitzer** [comment]
This has now been fixed.
