### ISSUE TITLE
should one file issues or submit corrections to the exercise/problem book?

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#33]
e.g., I found Sec 2.1, A-7, A-9, and A-11 all say "See the solution" **in the solution itself** (which is certainly bound to impress).

**Comment by arechnitzer** [comment]
What is compile date of the pdf you are looking at? And what page?

And - is the same problem present in the combined html/pdf version?

**Comment by cbm755** [comment]
28th Aug, standard alone, `clp_3_mc_problems.pdf`

But on closer look it appears I have mixed up "solutions" and "answers" which are apparently distinct.  Being a native English speaker (but one who doesn't read lengthy introductory sections) you can decide whether this is my problem or your's ;-)
