### ISSUE TITLE
"Differential" is not defined ("df" is, but not the word "differential")

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#42]
Exercises 14, 16, 17 in Section 2.6 explicit say "use the differential".

I think Definition 2.6.5 should use the word "differential" explicitly.  Perhaps it should also say "total differential"? (I'm less confident on this).

Also: Defn 2.6.5 fits with my own (rather loose) understanding of this idea.  But some people would find this definition imprecise.  From the footnote, I gather the informality is intentional.  But perhaps a citation to some analysis textbook for people who want to understand "df" and "dx" and "dy" more precisely?

- - - - 

In case its helpful, here's my slightly editorialized thought process on reading Defn 2.6.5:

> Ok so I don't know what a differential "df", let's read the definition....  Ok now I see how to replace it with two other other things "dx" and dy" which I guess are called either "differentials" or "infinitesimals", not sure which.  Maybe I'm suppose to know about those from last year...  I don't really understand this, but the writing style perhaps implies "other people" do this but perhaps not the authors and therefore not me.  My overall takeaway is this is some kind of optional notation that I think I can safely ignore and just use "∆f = ..."

**Comment by cbm755** [comment]
> Perhaps it should also say "total differential"?

How about "Some sources refer to $\textrm{d}f$ as the \emph{total differential} to emphasize that it corresponds to the overall change induces by small changes in $x$ and $y$"?

**Comment by cbm755** [comment]
In my opinion "df" is not approximately equal to 2.6.5 but exactly equal.  Its odd to have something defined as approximately equal to.

**Comment by joelfeldman** [comment]
Implemented.

**Comment by cbm755** [comment]
Reopening.  Assuming I'm reading the latest version, I still find this section vague and unhelpful:

![image](https://github.com/arechnitzer/CLP3/assets/818622/395dbd86-2069-4288-9d84-18dd7266308e)

- footnote: "don't take this notation too seriously"?   *cough* I think think this notation exists precisely in order to make something precise...

**Comment by cbm755** [comment]
concrete change requested: `df = `, not `\approx` in this definition of df.

**Comment by joelfeldman** [comment]
Upgraded Notation 2.6.5 and renamed it to Definition 2.6.5.
