### ISSUE TITLE
Chapter 1.7 Q5 Graph has mistake x=0 instead of y=0

### ISSUE THREAD

**Issue by youssef032** [arechnitzer/CLP3#43]
Line of y=0 should be drawn rather than x=0 (excluding the point (0,0)). Chapter 1.7

**Comment by arechnitzer** [comment]
Thanks for filing this. A little more information - is this in the solution or in the statement or...?

**Comment by youssef032** [comment]
It is in the graph of the solution.

**Comment by arechnitzer** [comment]
Ah yes - thanks. Did you also send a report to clpbugs@math.ubc.ca ?  You'll get a coffee card for spotting this.

**Comment by youssef032** [comment]
I did but I only got a reply saying thank you. How do I get the coffee card?

**Comment by arechnitzer** [comment]
The wheels turn slowly... but, you'll get an email from myself or @joelfeldman thanking you for the bug report, and some instructions on picking up the card from the maths department office.

**Comment by arechnitzer** [comment]
@youssef032 please make sure you send details of your course etc to clpbugs - as per the instructions at https://personal.math.ubc.ca/~CLP/Bounty/

**Comment by youssef032** [comment]
Done. Thank you Dr. Rechnitzer!
