### ISSUE TITLE
Poor formatting of 2.9.4 exercises stage 1 - Q1

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#46]
there is some overlapping text:

![Screenshot from 2022-07-06 13-25-29](https://user-images.githubusercontent.com/818622/177637008-66243018-6c35-42b9-9afa-60dd807748d5.png)

**Comment by cbm755** [comment]
That is in the HTML version: IIRC is looks ok in the PDF copy

**Comment by joelfeldman** [comment]
Fixed.
