### ISSUE TITLE
Missing "Q" in 2.9.4 exercises stage 1 - Q1

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#47]
There is a point Q in the picture but not in the exercise itself:

![Screenshot from 2022-07-06 13-27-59](https://user-images.githubusercontent.com/818622/177637184-a1d74b28-8eb3-467a-a6bb-a99ab58e0bab.png)

(great problem btw!)

**Comment by joelfeldman** [comment]
Fixed.
