### ISSUE TITLE
minor formatting problem of double hyphens

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#48]
See here in html file:

![Screenshot from 2022-07-06 13-27-59](https://user-images.githubusercontent.com/818622/177637300-984ac121-a796-4bc0-8911-b86ae24351cd.png)

There is some `y--axis` and `xy--plane` with double hyphens.  In LaTeX those would automatically become endashes: is something special required for same in PreTeXt?

**Comment by cbm755** [comment]
Here's an even more obnoxious case:

![Screenshot from 2022-07-06 13-32-19](https://user-images.githubusercontent.com/818622/177637897-9bcc1c0b-0832-4eb3-8f12-d1743149bdc3.png)

purple highlighting is me, ignore that

**Comment by joelfeldman** [comment]
Fixed
