### ISSUE TITLE
exercise CLP3 sec1.6 #23 maybe in the wrong place

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#50]
Cleaning up, found a note from after lecture: "CLP3 sec 1.6 #23 has unfair chain rule".

Out of context, but I have dim memory of discussing this with a student.  I think we decided that question required knowledge of Section 2.4 (the chain rule) in order to do the problem.  That is, its been copied from an old exam or something, looks like its about curves but really involves the chain rule in a way that students could not reasonably be expected to do while in Section 1.6.

**Comment by joelfeldman** [comment]
This requires only the CLP-1 chain rule. (Just treat each component separately.)
