### ISSUE TITLE
2.4 Q.27 part C uses confusing notation for partial derivative

### ISSUE THREAD

**Issue by ghost** [arechnitzer/CLP3#58]
![image](https://github.com/arechnitzer/CLP3/assets/146894924/3bc9b797-f75a-4d89-842d-80d207599f51)

(partialy/partialx)_u is very confusing notation for suggesting that u is being held constant.

![image](https://github.com/arechnitzer/CLP3/assets/146894924/fb37f4f6-f5b6-4e7b-b956-907a46f18708)

**Comment by joelfeldman** [comment]
I have expanded the solution to Q.27 part c in Section 2.4. The notation in question is defined in Notation 2.2.2 in the CLP-3 text.
