### ISSUE TITLE
1.1.1 Exercises — Stage 1 - Q2 has alphabet soup

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#6]
![Screenshot from 2020-05-11 16-42-09](https://user-images.githubusercontent.com/818622/81622643-62d1eb00-93a6-11ea-8deb-7d8ff9820a18.png)

No idea what each a, b, c, d, e refers to, esp refernces to "part (d)"... ummm which one?  There are 3 in this screenshot

**Comment by arechnitzer** [comment]
Okay - this is my fault for leaving debugging code in there.
Fixing.
